autocomplete_tag:
    path:     /autocomplete/tag
    controller: Tagwalk\ApiClientBundle\Controller\AutocompleteController::tag

autocomplete_designer:
    path:     /autocomplete/designer
    controller: Tagwalk\ApiClientBundle\Controller\AutocompleteController::designer

autocomplete_individual:
    path:    /autocomplete/individual
    controller: Tagwalk\ApiClientBundle\Controller\AutocompleteController::individual
