services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Tagwalk\ApiClientBundle\Form\ExportModelsType:
    arguments:
      $router: '@router'

  Tagwalk\ApiClientBundle\Form\ExportTagsType:
    arguments:
      $router: '@router'

  Tagwalk\ApiClientBundle\Provider\ApiProvider:
    autowire: false
    arguments:
      $baseUri:  ''
      $clientId: ''
      $clientSecret: ''
      $timeout: 10.0

  Tagwalk\ApiClientBundle\Serializer\Normalizer\HomepageNormalizer:
    tags: ['serializer.normalizer']
