services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Tagwalk\ApiClientBundle\Form\ExportModelsType:
    arguments:
      $router: '@router'

  Tagwalk\ApiClientBundle\Form\ExportTagsType:
    arguments:
      $router: '@router'

  Tagwalk\ApiClientBundle\Provider\ApiProvider:
    autowire: false
    arguments:
      $baseUri:  ''
      $clientId: ''
      $clientSecret: ''
      $timeout: 10.0

  Tagwalk\ApiClientBundle\Serializer\Normalizer\FileNormalizer:
    tags: ['serializer.normalizer']
    arguments:
      - '@serializer.name_converter.camel_case_to_snake_case'
      - '@serializer.property_accessor'

  Tagwalk\ApiClientBundle\Serializer\Normalizer\HomepageCellNormalizer:
    tags: ['serializer.normalizer']
    arguments:
      - '@serializer.name_converter.camel_case_to_snake_case'
      - '@serializer.property_accessor'
      - '@Tagwalk\ApiClientBundle\Serializer\Normalizer\FileNormalizer'

  Tagwalk\ApiClientBundle\Serializer\Normalizer\HomepageNormalizer:
    tags: ['serializer.normalizer']
    arguments:
      - '@serializer.name_converter.camel_case_to_snake_case'
      - '@serializer.property_accessor'
      - '@Tagwalk\ApiClientBundle\Serializer\Normalizer\HomepageCellNormalizer'

  Tagwalk\ApiClientBundle\Serializer\Normalizer\ExportNormalizer:
    tags: ['serializer.normalizer']
    arguments:
      - '@serializer.name_converter.camel_case_to_spinal_case'
      - '@serializer.property_accessor'

  serializer.name_converter.camel_case_to_spinal_case:
    class: 'Tagwalk\ApiClientBundle\Serializer\NameConverter\CamelCaseToSpinalCaseNameConverter'
